apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: catalogapi-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogapi-deployment
  targetCPUUtilizationPercentage: 12
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: basketapi-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: basketapi-deployment
  targetCPUUtilizationPercentage: 12
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: discountapi-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discountapi-deployment
  targetCPUUtilizationPercentage: 12
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: discountgrpc-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discountgrpc-deployment
  targetCPUUtilizationPercentage: 12
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orderingapi-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orderingapi-deployment
  targetCPUUtilizationPercentage: 12
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ocelotapigw-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ocelotapigw-deployment
  targetCPUUtilizationPercentage: 12
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingaggregator-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingaggregator-deployment
  targetCPUUtilizationPercentage: 12
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingapp-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingapp-deployment
  targetCPUUtilizationPercentage: 12