apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi-deployment
  labels:
    app: catalogapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
        - name: catalogapi
          image: shoppingmicroservicesacr.azurecr.io/catalogapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
            - name: DatabaseSettings__DatabaseName
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: database_name
            - name: DatabaseSettings__CollectionName
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: collection_name
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  selector:
    app: catalogapi
  ports:
    - protocol: TCP
      port: 80