apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc-deployment
  labels:
    app: discountgrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountgrpc
  template:
    metadata:
      labels:
        app: discountgrpc
    spec:
      containers:
        - name: discountgrpc
          image: ecommercemicroservicesacr.azurecr.io/discountgrpc:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: postgres-configmap
                    key: connection_string
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: discountgrpc-service
spec:
  selector:
    app: discountgrpc
  ports:
    - protocol: TCP
      port: 80