apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlserver-secret
                key: sa-password
          - name: ACCEPT_EULA
            value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433