version: '3.9'

services:
  catalogdb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ~/apps/mongo:/data/db
        
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - '8081:8081'
    depends_on:
        - redis

  catalogapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalogdb
  
volumes:
  redis-data: