version: '3.9'

services:
  catalog-db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ~/apps/mongo:/data/db
        
  basket-db:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    
  basket-api:
    build:
      context: .
      dockerfile: Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket-db:6379"
    ports:
      - "8001:80"
    depends_on:
      - basket-db

  catalog-api:
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalog-db:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalog-db