apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: ZWNvbW1lcmNlbWljcm9zZXJ2aWNlc21vbmdvZGJ1c2VybmFtZQ==
  mongo-root-password: ZWNvbW1lcmNlbWljcm9zZXJ2aWNlc21vbmdvZGJwYXNzd29yZA==