apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: ZWNvbW1lcmNlbWljcm9zZXJ2aWNlc3Bvc3RncmVzdXNlcg==
  postgres-password: ZWNvbW1lcmNlbWljcm9zZXJ2aWNlc3Bvc3RncmVzcGFzc3dvcmQ=
  postgres-db: ZWNvbW1lcmNlbWljcm9zZXJ2aWNlc3Bvc3RncmVzZGF0YWJhc2U=