apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  connection_string: Server=postgres-service;Port=5432;Database=ecommercemicroservicespostgresdatabase;User Id=ecommercemicroservicespostgresuser;Password=ecommercemicroservicespostgrespassword;