apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingaggregator-deployment
  labels:
    app: shoppingaggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingaggregator
  template:
    metadata:
      labels:
        app: shoppingaggregator
    spec:
      containers:
        - name: shoppingaggregator
          image: riannegreiros/ecommercemicroserviceshoppingaggregator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ApiSettings__CatalogtUrl
              valueFrom:
                configMapKeyRef:
                  name: shoppingaggregator-configmap
                  key: catalogapi_url
            - name: ApiSettings__BasketUrl
              valueFrom:
                configMapKeyRef:
                  name: shoppingaggregator-configmap
                  key: basketapi_url
            - name: ApiSettings__OrderingUrl
              valueFrom:
                configMapKeyRef:
                  name: shoppingaggregator-configmap
                  key: orderingapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingaggregator-service
spec:
  type: NodePort
  selector:
    app: shoppingaggregator
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 80
      nodePort: 30500